### ISSUE TITLE
Errors, not compiling

### ISSUE THREAD

**Issue by RealPetChicken** [designrifts/Ultimate_Theme_UI_Template#8]
So the errors i am getting is 10:
PagerSlidingTabStrip cannot be resolved to a type          IconActivity.java
The import com.astuetz.viewpager cannot be resolved  IconActivity.java

I have added the CardsUI Library, PagerSlidingTabStrip Library as well, and still no go. Any help will be appreciated.

Here is my post on XDA developers: http://forum.xda-developers.com/showpost.php?p=50896090&postcount=73

**Comment by alighazi** [comment]
you have to rename the line 
import com.astuetz.viewpager.extensions.PagerSlidingTabStrip; 
to
import com.astuetz.PagerSlidingTabStrip; 

Hope it helps

**Comment by designrifts** [comment]
I apologize, I did not get the email on the original issue, only this reply. Please let me know if you have resolved your issue.

**Comment by RealPetChicken** [comment]
i did, thanks.
